Update workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -34,6 +34,20 @@ jobs:
             echo "::error ::Unable to determine last published framework version, aborting run"
             exit 1
           fi
+
+          LATEST_OPENSSL_IOS_RELEASE=$(gh api /repos/tls-inspector/openssl-ios/releases/latest --jq '.name')
+          if [ -z "$LATEST_OFFICIAL_OPENSSL_RELEASE" ]; then
+            echo "::error ::Unable to determine latest openssl version, aborting run"
+            exit 1
+          fi
+          if [ -z "$LATEST_OPENSSL_IOS_RELEASE" ]; then
+            echo "::error ::Unable to determine last published framework version, aborting run"
+            exit 1
+          fi
+
+          echo "CURL_VERSION=${LATEST_CURL_IOS_RELEASE}" >> $GITHUB_OUTPUT
+          echo "OPENSSL_VERSION=${LATEST_OPENSSL_IOS_RELEASE}" >> $GITHUB_OUTPUT
+
           echo "::notice ::Latest curl release: ${LATEST_OFFICIAL_CURL_RELEASE}, last published framework: ${LATEST_CURL_IOS_RELEASE}"
           echo "curl_version=${LATEST_OFFICIAL_CURL_RELEASE}" >> $GITHUB_OUTPUT
           if [[ "${LATEST_CURL_IOS_RELEASE}" != "${LATEST_OFFICIAL_CURL_RELEASE}" ]]; then
@@ -55,6 +69,9 @@ jobs:
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #pin v4.2.2
       - name: Compile Framework
         id: compile
+        env:
+          CURL_VERSION: ${{ needs.query.outputs.CURL_VERSION }}
+          OPENSSL_VERSION: ${{ needs.query.outputs.OPENSSL_VERSION }}
         run: |
           gpg --import ./curl.asc
           echo 'trusted-key 0x78E11C6B279D5C91' >> ~/.gnupg/gpg.conf
@@ -82,5 +99,7 @@ jobs:
           rm -f private_key.pem
       - name: Make Release
         id: make_release
+        env:
+          GH_TOKEN: ${{ github.token }}
         run: |
           gh release create -n "${{ needs.query.outputs.curl_version }}" -t "${{ needs.query.outputs.curl_version }}" ${{ needs.query.outputs.curl_version }} curl.xcframework.zip curl.xcframework.zip.sig curl_swift.xcframework.zip curl_swift.xcframework.zip.sig
